; flyway.user=postgres
; flyway.password=example
; flyway.schemas=public
; flyway.url=jdbc:postgresql://172.19.0.2:5432/vallia_docflow_dev
; flyway.locations=filesystem:src/main/resources/db/migration
; flyway.validateMigrationNaming=true


    