springdoc:
  api-docs:
    path: /api-docs
  info: Vallia DocIntel
  packagesToScan: com.brimmatech.apps.deapi.controller,com.brimmatech.docflow.hooks
  swagger-ui:
    path: /welcome
    url: /api-docs
    server-item-url: ${DOC_INTEL_SWAGGER_CONTEXT_PATH:/}
#    disable-swagger-default-url: true
#    api-docs.path: /

server:
  port: ${PORT:8080}

management:
  endpoint.health.group.custom.include: diskSpace,ping,titleConnectSyncerService
  endpoint.health.group.custom.show-components: always
  endpoint.health.group.custom.show-details: always
  endpoint.health.show-details: always
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,info,prometheus,metrics,alertConfig,refresh,env"
  endpoint:
    env:
      post:
        enabled: true
    prometheus:
      enabled: true
    health:
      validate-group-membership: false

spring:
  mvc:
    pathmatch:
      use-trailing-slash-match: true
  session:
    store-type: jdbc
    jdbc:
    initialize-schema: never

  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  mail:
    host: ${EMAIL_HOST:smtp.gmail.com} # or smtp.gmail.com
    port: ${EMAIL_PORT:587}                 # TLS port
    username: ${EMAIL_USERNAME:maheswariks@brimmatech.com} # your email address
    password: ${EMAIL_PASSWORD:gsfxvrcrehyqdfbz}      # app password, not your normal password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 1000

  boot:
    mainclass: com.brimmatech.apps.deapi.DocExtractionApiApplication

  profiles:
    active: ${APP_PROFILE:dev}
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:500MB}
      max-request-size: ${MAX_REQUEST_SIZE:500MB}
  datasource:
    url: ${docflow-database-url}
    driver-class-name: ${docflow-database-driver-class}
    username: ${docflow-database-username}
    password: ${docflow-database-password}
    connectionProperties: 'ApplicationName=application-name-test'
    hikari:
      # Numbers in inline #comments are defaults
      minimum-idle: 5
      maximum-pool-size: 20 #10
      idle-timeout: 600000 #600000
      connection-timeout: 30000 #30000
      leak-detection-threshold: 10000 #0
      max-lifetime: 1800000 #1800000
      poolName: "orchestrator-local"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      format-sql: true
      globally_quoted_identifiers: true
      connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
      ddl-auto: validate

    properties:
      hibernate:
        type: trace
  service-bus:
    enabled: ${ENABLE_SERVICE_BUS}
    connection-string: ${docflow-bus-url}
    classifier-queue-name: ${DOC_CLASSIFIER_QUEUE_NAME}
    webhook-event-queue-name: ${WEBHOOK_EVENT_QUEUE_NAME}

  flyway:

    schemas: public
    url: ${docflow-database-url}
    user: ${docflow-database-username}
    password: ${docflow-database-password}

    enabled: true                      # Optional (true by default)
    baseline-on-migrate: true         # Prevents error on non-empty schema
    baseline-version: 1
    locations: db/migration  # Custom migration location (optional)
    validateMigrationNaming: true

  ai:
    chat:
      client:
        observations:
          enabled: true
          log-prompt: true
          log-completion: true
          include-error-logging: true
      memory:
        repository:
          jdbc:
            initialize-schema: never
    tools:
      observations:
        include-content: false
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers/mcp_tools.json
    azure:
      openai:
        endpoint: ${AZURE_API_BASE}
        api-key: ${AZURE_API_KEY}
        deployment-name: gpt-4o
        temperature: 0.01

  cloud:
    config:
      enabled: false

    azure:
      keyvault:
        secret:
          enabled: false
          property-source-enabled: false
          property-sources[0]:
            enabled: true
            endpoint: ${AZURE_KEYVAULT_URI}

sftp:
  host: ${SFTP_HOST}
  port: ${SFTP_PORT:22}
  username: ${SFTP_USERNAME}
  password: ${SFTP_PASSWORD}
  remote-dir: ${SFTP_REMOTE_DIR}


api:
  meridian-link:
    host: ${MERIDIAN_HOST:https://webservices.mortgage.meridianlink.com}
    auth-url: ${MERIDIAN_URL:/los/webservice/AuthService.asmx}
    username: ${MERIDIAN_USERNAME}
    password: ${MERIDIAN_PASSWORD}
    run-method-url: ${MERIDIAN_RUN_METHOD:/los/webservice/edocsservice.asmx}
    soap-action: ${MERIDIAN_SOAP_ACTION:http://www.lendersoffice.com/los/webservices/ListEdocsByLoanNumber}
    endpoint:
      fetch-all-document-uri: /los/webservice/edocsservice.asmx
  byte:
    site: ${BYTE_API_BASE_URLS}
    host: ${BYTE_API_BASE_URL:https://hosting.bytesoftware.com}
    endpoint:
      token-uri: /${BYTE_SITE_NAME}/byteapi/auth
    authorization-key: ${BYTE_AUTH_KEY}
  teams:
    enabled: ${ENABLED_TEAMS_NOTIFICATIONS:false}
    webhookUrl: ${WEBHOOK_URL:https://brimmatech1.webhook.office.com/webhookb2/ebde754a-74ab-4ffd-a0d7-9584285eb40b@9d67d2f5-a1d9-4d8f-a91d-1c5d78fa3a61/IncomingWebhook/93ba75b49ad74099a5dda58add2e8278/84c2bb53-bccf-4e5c-a30c-53a4a4fc1dc8/V2V34AELzhFgM4X-iLK1960lyrd8PenICjfkISv8VB4UA1}
  encompass:
    host: https://api.elliemae.com/
    endpoint:
      generate-print-order-url: /encompassdocs/v1/documentOrders/ondemand
      retrieve-print-order-url: /encompassdocs/v1/documentOrders/ondemand/{orderId}
      token-uri: oauth2/v1/token
      fetch-loan: /encompass/v3/loans/{loanGuid}
      fetch-loan-uri: /encompass/v3/loans/{loanGuid}/fieldReader
      simple-pipeline-query: /encompass/v3/loanPipeline
      fetch-all-document-uri: /encompass/v3/loans/{LoanGuid}/documents?includeRemoved=false
      create-document-uri: /encompass/v3/loans/{LoanGuid}/documents?action=add&view=entity
      get-document-uri: /encompass/v3/loans/{loanId}/documents/{documentId}
      add-comment-uri: /encompass/v3/loans/{LoanGuid}/documents/{documentId}/comments?action=add&view=entity
      retrieve-lock-uri: /encompass/v1/resourceLocks
      unlock-resource-uri: /encompass/v1/resourceLocks/{LockId}
      update-loan-uri: /encompass/v3/loans/{LoanGuid}?view=entity
      fetch-document-attachment: /encompass/v1/loans/{LoanGuid}/documents/{DocumentId}/attachments
      fetch-attachment-detail: /encompass/v3/loans/{LoanGuid}/attachments/{AttachmentId}
      fetch-all-attachments-uri: /encompass/v3/loans/{LoanGuid}/attachments
      fetch-attachment-download-url-detail: /encompass/v3/loans/{LoanGuid}/attachmentDownloadUrl
      field-writer-uri: /encompass/v3/loans/{LoanGuid}/fieldWriter
      enhanced-condition-update-uri: /encompass/v3/loans/{loanGuid}/conditions
      post-closing-condition-update-uri: /encompass/v1/loans/{loanGuid}/conditions/postclosing
      lock-resource-uri: /encompass/v1/resourceLocks?view=id
      remove-document-attachment: /encompass/v3/loans/{LoanGuid}/attachments?action=remove
      mismo-conversion: /services/v1/transformer?loanId={LoanGuid}&format={formatType}
      fetch-underwriting-conditions: /encompass/v1/loans/{LoanGuid}/conditions/underwriting
      fetch-preliminary-conditions: /encompass/v1/loans/{LoanGuid}/conditions/preliminary
      fetch-postclosing-conditions: /encompass/v1/loans/{LoanGuid}/conditions/postclosing?view=entity&isRemoved=true
      fetch-users: /encompass/v1/company/users
      fetch-efolder: /encompass/v3/settings/efolder/documents
      dt-logs: /encompass/v3/loans/{LoanGuid}/disclosureTracking2015Logs
      dt-logs-patch: /encompass/v3/loans/{LoanGuid}/disclosureTracking2015Logs/{DisclosureTrackingId}?view=entity
      create-export-job: /efolder/v1/loans/{loanId}/exportJobsCreator
      v3-assign-document-attachments: /encompass/v3/loans/{loanId}/documents/{documentId}/attachments
      get-export-job-status: /efolder/v1/exportjobs
      standard-condition: /encompass/v1/loans/{{loanId}}/conditions/{{underwriting}}/{{ConditionId}}/comments?action=add&view=entity
      enhanced-condition: /encompass/v3/loans/{{loanId}}/conditions/{{ConditionId}}/comments?action=add&view=entity
  pluto-querier:
    endpoint:
      fetch-purchase-advice-document-fields: ${FETCH_PURCHASE_ADVICE_DOCUMENT_FIELDS:v2/get-field-details}
      fetch-purchase-condition-request: ${FETCH_PURCHASE_CONDITION_REQUEST:v2/get-enhanced-condition-details}
  los-service:
    host: ${LOS_SERVICE_BASE_URL:https://brimma-valllia-docflow-los-svc-stage-as.azurewebsites.net/}
    attachment-upload-url: losservice/api/v1/Document/{tenantId}/upload?loanGuid={loanGuid}&sorName={sorName}
    assign-source-attachment-url: losservice/api/v1/Document/{tenantId}/assignSourceAttachmentsToDestination
  doc-processor:
    host: ${DOC_PROCESSOR_BASE_URL:https://brimma-vallia-docflow-doc-processor-stage-as.azurewebsites.net/}
    invoke-agent: ${INVOKE_AGENT:/api/v1/agent/vallia-ask}
    create-thread: ${CREATE_THREAD_URI:/api/v1/agent/create-thread}
    delete-thread: ${DELETE_THREAD_URI:/api/v1/agent/delete-thread}
    history: ${THREAD_HISTORY:/api/v1/agent/thread/history}
  message-processor:
    base-url: ${MESSAGE_PROCESSOR_BASE_URL:https://brimma-vallia-docflow-ruleengine-dev-as.azurewebsites.net/docflow-events-publisher}
    post-message-uri: /api/post-message

mail:
  hostname: ${MAIL_HOST:smtp.office365.com}
  port: ${MAIL_PORT:587}
  smtp_auth_enabled: true
  smtp_tls_enabled: true
  username: ${MAIL_USERNAME:test@brimmapa.onmicrosoft.com}
  password: ${MAIL_PASSWORD:Xuy57460}
  to_addresses: ${MAIL_TO}
  cc_addresses: ${MAIL_CC}
  subject: ERROR MESSAGE - Loan Locked Regarding
  provider: ${MAIL_PROVIDER:OUTLOOK}
  tls_protocol: ${MAIL_TLS_PROTOCOL:TLSv1.2}
  connectionTimeout: ${MAIL_CONNECTION_TIMEOUT:100000}
  ssl_protocol: ${MAIL_SSL_PROTOCOL:smtp}
app:
  job:
    indexing:
      enabled: ${INDEXING_JOB_ENABLED:false}
      cron: ${INDEXING_JOB_CRON:0 */5 * * * ?}
      startDate: ${INDEXING_START_DATE:2026-02-03}
  zipkin:
    host: ${ZIPKIN_URL:http://localhost:8080/api/v2/spans}
  rpa:
    connection-url: https://prod-24.westus.logic.azure.com:443/workflows/49bc51a22e6f467daf0db2cf18976270/triggers/manual/paths/invoke?api-version=2016-06-01&sp=/triggers/manual/run&sv=1.0&sig=CJOaIy-qXVHxs6EeGPmJI02skzXvpyayaUSBG3ZS878
  crypto:
    encryption-algorithm: AES/ECB/PKCS5Padding
    encryption-key: WEc#HCt<mC)Sw7(
    algorithm: AES
    length: 16
    message-digest-algorithm: SHA-1

  blob:
    connection-string: ${docflow-blob-connection-string}
    container-name: ${CONTAINER_NAME:docflow}
  v2:
    json-rule-engine-url: ${RULE_ENGINE_URL:https://brimma-vallia-docflow-pluto-prod-as.azurewebsites.net}
    json-neptune-rule-engine-url: ${NEPTUNE_ENGINE_URL:https://vallia-docflow-neptune-node-dev-as.azurewebsites.net}

  client_assertion:
    signer_keyvault: https://kv-brimma-dev.vault.azure.net/
    #signer_key: jwt-signing-key

  classification:
    page_caching: false
    dump_whole_pages_when_total_pages_eq: 2

  package_processing:
    default_file_name_template: ${DEFAULT_FILE_NAME_TEMPLATE:<span th:text="${documentId + '_' + fileName + '_' + startPage + '_to_' + endPage + '.pdf'}"></span>}


spring.config:
  import: optional:classpath:/git.properties

docintel.config:
  extraction.confidence_upper_limit: ${EXTRACTION_CONFIDENCE_UPPER_LIMIT:0.90}
  classification.confidence_upper_limit: ${CLASSIFICATION_CONFIDENCE_UPPER_LIMIT:0.90}
azure_chat:
  endpoint: https://brimma-vallia-ai-dev-oa.openai.azure.com/openai/deployments/gpt-4/chat/completions?api-version=2024-08-01-preview
  langChainEndpoint: https://brimma-vallia-ai-dev-oa.openai.azure.com
  app_key: ${docflow-azure-ai-chatbot-api-key}

openai.assistants_api:
  endpoint: ${OPEN_AI_ASSISTANT_API_ENDPOINT:${AZURE_API_BASE}}
  api_key: ${docflow-open-ai-assistant-api-key}
  #assistantName: SelfEmploymentIncomeCalcV3
  assistantId: ${ASSISTANT_ID:asst_K7yyZawTtuagmjJe6SlijAAg}
  #vectorStoreName: EmploymentIncomeCalcV3.6
  vectorStoreId: ${VECTOR_STORE_ID:vs_ZFc5jQIynXeTLCSoLCOPvrxy}
#  can you perform the analysis based on the docs in the vector store as instructed in the system prompt

tenant:
  credential:
    profile: ${TENANT_CREDENTIAL_PROFILE:local}


azure_form_recognizer:
  endpoint: ${AZURE_DOC_EXTRACTION_ENDPOINT}
  app_key: ${docflow-azure-doc-extraction-api-key}
azure_document_classification:
  split_mode: ${AZURE_DOC_CLASSIFICATION_SPLIT_MODE:none}
  endpoint: ${AZURE_DOC_CLASSIFICATION_ENDPOINT:https://valliadocai.cognitiveservices.azure.com}
  model-id: ${AZURE_DOC_CLASSIFICATION_MODEL_ID:vallia_docintel_dc_v7.0.0}
  ocp-subscription-key: ${docflow-ocp-apim-subscription-key}
azure_content_understanding:
  endpoint: ${AZURE_CONTENT_UNDERSTANDING_ENDPOINT}
  app_key: ${docflow-azure-content-understanding-api-key}
azure_agent:
  connectionString: ${AGENT_CONNECTION_STRING:eastus2.api.azureml.ms;02f9d2d4-e049-4eb5-b22f-b3163a9875cd;brimma-vallia-ai-ask-and-analyze-dev-rg;vallia-ask-and-analyze}
  agentId: ${AGENT_ID:asst_HRGy5NMYsKHjyEAABDXEOj7c}



azure:
  keyvault:
    client-id: ${AZURE_KEYVAULT_CLIENT_ID}
    client-key: ${AZURE_KEYVAULT_CLIENT_KEY}
    tenant-id: ${AZURE_KEYVAULT_TENANT_ID}
    enabled: ${AZURE_KEYVAULT_ENABLED}
    uri: ${AZURE_KEYVAULT_URI}
#    uri: https://docflow-local-saro.vault.azure.net



#langchain4j.open-ai.chat-model.log-requests: true
#langchain4j.open-ai.chat-model.log-responses: true


logging:
  level:
    root: ERROR
    dev:
      langchain4j: TRACE
      ai4j.openai4j: DEBUG
    org.hibernate: ERROR
    com.zaxxer.hikari: ERROR
    no.skatteetaten: DEBUG
    org.flywaydb: INFO
    org.springframework.scheduling.concurrent: ERROR
    org.springframework.security: INFO
    org.springframework.cloud: ERROR
    com.azure.security.keyvault: ERROR
    org.springframework.boot: ERROR


    org.springframework.web: INFO
    #org.springframework.web.servlet: ERROR
    com.brimmatech: DEBUG
    org.hibernate.orm.jdbc.bind: OFF
    org:
      springframework:
        cloud:
          context:
            scope:
              refresh: DEBUG
        ai: INFO
        ai.chat:
          client:
            advisor: DEBUG
      apache:
        pdfbox:
          filter:
            DCTFilter: WARN
    com.brimmatech.general.types.ThrowingSupplier: ERROR # DEBUG logs captured exceptions
    com:
      brimmatech:
        general:
          config: DEBUG
    com.brimmatech.backgroundservices: OFF
    com.brimmatech.docflow.v2.task.listeners: OFF
    com.brimmatech.docflow.v2.task.requestgenerators: DEBUG
    com.brimmatech.docflow.extraction.mle: TRACE

    com.brimmatech.docflow.classification.assistants.DocTypeExplainer: DEBUG
    com.brimmatech.docflow.classification.assistants.PageFeederAssistant: DEBUG
    com.brimmatech.mcp.PlanningResultsHolder: TRACE

    #    com.brimmatech.docflow.v2.task.repository: TRACE
    com.azure.core: OFF
    #    com.azure.core.http: TRACE
    com.azure.ai.documentintelligence: TRACE # Extraction and classification
    com.fasterxml.jackson: OFF
    reactor.netty.http.client: OFF
    org.testcontainers: DEBUG

docflow.taskConfig:
  limiterBounds: ${AI_TASKS_LIMITER_BOUND}
  noOfWorkers: ${AI_TASKS_WORKERS_COUNT}

info.app.name: DocFlow Rule Orchestrator/Engine.
info.app.id: com.brimmatech.orchestrator.
info.app.description: "There are two versions: Self Rule evaluation by EvalEx and JsonRulesEngine(Pluto)"
info.app.version: 1.0.0
info.app.deploy_environment: ${ORCHESTRATOR_DEPLOY_ENV}
info.app.deploy_url: ${ORCHESTRATOR_URL:http://localhost:8081}
az.http.logging.level: BODY_AND_HEADERS

task:
  uploadSavePath: ${UPLOAD_SAVE_DIR:/tmp}
  tenant:
    name: ${TASK_SUPPORT_TENANTS:BRIMMAA,WILQO,EMPORIUM}
    flowName: ${TASK_SUPPORT_FLOW_NAME}

docflow-azure-ai-chatbot-api-key: ${AZURE_AI_CHATBOT_API_KEY}
docflow-azure-content-understanding-api-key: ${AZURE_CONTENT_UNDERSTANDING_API_KEY}
docflow-azure-doc-extraction-api-key: ${AZURE_DOC_EXTRACTION_API_KEY}
docflow-blob-connection-string: ${BLOB_CONNECTION_STRING}
docflow-bus-url: ${DOC_FLOW_BUS_URL}
docflow-database-driver-class: ${DATABASE_DRIVER_CLASS}
docflow-database-password: ${DATABASE_PASSWORD}
docflow-database-url: ${DATABASE_URL}
docflow-database-username: ${DATABASE_USERNAME}
docflow-ocp-apim-subscription-key: ${OCP_APIM_SUBSCRIPTION_KEY}
docflow-open-ai-assistant-api-key: ${AZURE_OPENAI_API_KEY}

ask-and-analyze:
  pipeline:
    folders: ${ASK_AND_ANALYZE_PIPELINE_FOLDERS:Active Loans}

global:
  tenantId: ${GLOBAL_TENANT_ID:9}

pa-ps:
  open-ai-assistant: ${PA_OPEN_AI_ASSISTANT_ENDPOINT:https://vallia-docflow-openai.openai.azure.com/}
  open-ai-api-key: ${PA_OPEN_AI_API_KEY:88AXBEoRhSRhTR0MQL3dFhhsTTRFZj2yka2C8eyl05a6aFY6Z6Z0JQQJ99BGACYeBjFXJ3w3AAABACOGrDhr}
  open-ai-assistant-id: ${PA_ASSISTANT_ID:asst_wDuxkSMe3YTb8n9bAoBOMCIi}
genie:
  config:
    root: ${GENIE_CONFIG_ROOT}
BayEquity:
  loans-batch-size: ${BE_LOAN_BATCH_SIZE:50}
  closing-package:
    Batch-size: ${NUM_PER_BATCH:2}
    to-be-process-in: ${PROCESS_ENV:dev}
princeton-custom-ui: ${PRINCETON_CUSTOM_UI_URL:https://princeton-dashboard-ui-dev-as.azurewebsites.net/dashboard}
princeton-enable-prod-email: ${SEND_EMAIL_TO_LO:false}
loan-summary-cron: ${LOAN_SUMMARY_CRON:0 0 10 * * MON-FRI}
princeton-condition-uri: ${PRINCETON_CONDITION_UI_URL:https://princeton-dashboard-prod-ui-as.azurewebsites.net/conditions/}
