package com.brimmatech.encompass.loanreader.encompass.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Data;

@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ClosingDisclosure3{
	private String fromToBorrower;
	private Object actualStdleDepositFromLatestRec;
	private Object stdFinalTotalClosingCostJ;
	private Object finalCashToClose;
	private Object stdFinalClosingCostFinanced;
	private String stdFundsForBorrowerDidChangeCol;
	private String fromToSeller;
	private Object stdleTotalClosingCostJ;
	private Object stdleDeposit;
	private String altClosingCostBeforeClosingDidChangeCol;
	private Object liabilityTotal;
	private Object actualStdleClosingCostFinancedFromLatestRec;
	private Object totalFromN;
	private Object stdFinalAdjustmentAndOtherCredits;
	private String stdTotalClosingCostBeforeClosingDidChangeCol;
	private Object cd3TotalClosingCostJ;
	private Object stdleClosingCostFinanced;
	private Object stdFinalFundForBorrower;
	private Object lecd3TotalPayoffsAndPaymentsK;
	private Object actualStdleSellerCreditsFromLatestRec;
	private Object closingCostsPaidatClosingJ;
	private String stdSellerCreditsDidChangeCol;
	private Object cash;
	private String stdDownPaymentDidChangeCol;
	private String altTotalClosingCostRemark;
	private String stdTotalClosingCostDidChangeCol;
	private Object actualStdleFundForBorrowerFromLatestRec;
	private Object actualLecd3TotalClosingCostJFromLatestRec;
	private Object actualLeLoanAmountFromLatestRec;
	private Object stdFinalSellerCredits;
	private Object totalDuetoSelleratClosingM;
	private Object closingCostsPaidAtClosing;
	private Object stdleFundForBorrower;
	private Object ucdkSubTotal;
	private Object cd3CashToClose;
	private Object stdFinalDownPayment;
	private Object actualStdleAdjustmentAndOtherCreditsFromLatestRec;
	private boolean excludeBorrowerClosingCosts;
	private String altTotalPayoffsDidChangeCol;
	private String stdDepositDidChangeCol;
	private Object ucdTotalAdjustmentsAndOtherCredits;
	private String stdTotalClosingCostRemark;
	private Object stdFinalCd3ClosingCostsPaidBeforeClosing;
	private String altCashToCloseDidChangeCol;
	private String stdClosingCostFinancedDidChangeCol;
	private Object actualStdleTotalClosingCostJFromLatestRec;
	private Object stdleCashToClose;
	private Object lecd3CashToClose;
	private Object lecd3TotalClosingCostJ;
	private Object cd3TotalPayoffsAndPaymentsK;
	private Object leLoanAmount;
	private boolean newVerbiageDisclosed;
	private Object totalPaidAlreadybyoronBehalfofBoroweratClosing;
	private String stdAdjustmentsDidChangeCol;
	private String lecd3CashToCloseFromToBorrower;
	private Object stdleCd3ClosingCostsPaidBeforeClosing;
	private Object nonUcdTotalAdjustmentsAndOtherCredits;
	private Object stdleAdjustmentAndOtherCredits;
	private Object cashToClose;
	private Object actualLecd3TotalPayoffsAndPaymentsKFromLatestRec;
	private Object ucdlSubTotal;
	private Object totalDuefromBorrowerAtClosing;
	private Object stdleDownPayment;
	private Object actualStdleDownPaymentFromLatestRec;
	private Object cd3ClosingCostsPaidBeforeClosing;
	private String altLoanAmountDidChangeCol;
	private Object totalFromM;
	private Object totalFromL;
	private Object totalFromK;
	private Object loanAmount;
	private String cd3CashToCloseFromToBorrower;
	private Object lecd3ClosingCostsPaidBeforeClosing;
	private Object stdFinalDeposit;
	private Object totalDuefromSelleratClosingN;
	private String altTotalClosingCostDidChangeCol;
	private Object totalAdjustmentsAndOtherCredits;
	private Object stdleSellerCredits;
}