package com.brimmatech.docflow.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum TaskFailures {
    ERR_EXTRACTION_MODEL_NOT_FOUND("ERR_EXTRACTION_MODEL_NOT_FOUND"),
    @Deprecated
    INTERNAL_ERROR("INTERNAL_ERROR"),
    EMPTY_PAGE_CONTENT("EMPTY_PAGE_CONTENT"),
    ERROR_UPDATE_INPUT("ERROR_UPDATE_INPUT"),
    NO_DOC_PROCESSING_RESULTS_ENTITY("NO_DOC_PROCESSING_RESULTS_ENTITY"),
    NO_LOAN_OR_TENANT_ID("NO_LOAN_OR_TENANT_ID"),
    NO_INPUT("NO_INPUT"),
    CACHE_LOOKUP_FAILED("CACHE_LOOKUP_FAILED"),
    DOC_OCR_PARSING("DOC_OCR_PARSING"),
    DOC_UPSTREAM_PROCESSING("DOC_UPSTREAM_PROCESSING"),
    NO_DOC_META("NO_DOC_META"),
    NO_FIELDS_FOR_EXTRACTION("NO_FIELDS_FOR_EXTRACTION"),
    NO_BLOB_URL("NO_BLOB_URL"),
    UPLOAD_BLOB("UPLOAD_BLOB"),
    NO_HOOK_CONFIG("NO_HOOK_CONFIG"),
    NO_REQUEST_FACTORY("NO_REQUEST_FACTORY"),
    NO_DEX_ENTITY("NO_DEX_ENTITY"),
    ERROR_UPDATE_OUTPUT("ERROR_UPDATE_OUTPUT"),
    MAX_RETRIES("MAX_RETRIES"),
    NO_ATTACHMENTS("NO_ATTACHMENT"),
    INVESTOR_NOT_CONFIGURED("INVESTOR_NOT_CONFIGURED"),
    UNABLE_TO_FIND_TASK_TREE("UNABLE_TO_FIND_TASK_TREE"),
    VALIDATION_FAILED("VALIDATION_FAILED"),
    RESOLVE_FIELD_TARGETS_FAILED("RESOLVE_FIELD_TARGETS_FAILED"),
    RESOLVE_FIELD_TARGETS_OUTSIDE_DOC_BOUNDS("RESOLVE_FIELD_TARGETS_OUTSIDE_DOC_BOUNDS"),
    NO_CHANGE_LEDGER_INPUT("NO_CHANGE_LEDGER_INPUT"),
    //LLM
    EMPTY_LLM_RESPONSE(""),
    MULTIPLE_SHIPPING_PACKAGE("MULTIPLE_SHIPPING_PACKAGE"),
    RTY_NO_SHIPPING_PACKAGE_OR_DOC_ID("RTY_NO_SHIPPING_PACKAGE_OR_DOC_ID"),
    NO_ROUTING_META("NO_ROUTING_META"),
    SFTP_UPLOAD_FAILED("SFTP_UPLOAD_FAILED"),
    SFTP_SESSION_FAILED("SFTP_SESSION_FAILED"),
    NO_DOC_EX_FOUND("NO_DOC_EX_FOUND"),
    IMAGE_WRITE_FAILED("IMAGE_WRITE_FAILED"),
    ENCOMPASS_LOAN_LOCKED("ENCOMPASS_LOAN_LOCKED"),
    ENCOMPASS_FIELD_UPDATE_ERROR("ENCOMPASS_FIELD_UPDATE_ERROR"),
    INVALID_TASK_INPUT("INVALID_TASK_INPUT");
    private String name;
}
