package com.brimmatech.general.config;

import lombok.Getter;

@Getter public enum RoutingTypes {

    EXEC_RULES("EXEC_RULES"),
    EXTRACT_UPLOADED_DOCS("EXTRACT_UPLOADED_DOCS"),
    ON_LOAN_MODIFIED_RULE_EXECUTION("ON_LOAN_MODIFIED_RULE_EXECUTION"),
    SPLIT_UPLOADED_DOCS("SPLIT_UPLOADED_DOCS"),
    NOOP_SUPERVISOR_CHECK("NOOP_SUPERVISOR_CHECK"),
    PURCHASE_ADVICE("PURCHASE_ADVICE"),
    GENIE_SYNC("GENIE_SYNC"),
    CLASSIFY_VIA_TWO_STEP("CLASSIFY_VIA_TWO_STEP"),
    PURCHASE_CONDITION("PURCHASE_CONDITION"),
    EXTRACT_UPLOADED_DOCS_USING_CONTENT_UNDERSTANDING("EXTRACT_UPLOADED_DOCS_USING_CONTENT_UNDERSTANDING"),
    DYNAMIC_EXTRACTION_ANALYSIS("DYNAMIC_EXTRACTION_ANALYSIS"),
    INTENT_TO_PROCEED("INTENT_TO_PROCEED"),
    SIGNED_DISCLOSURES("SIGNED_DISCLOSURES"),
    PLAYGROUND_CLASSIFY("PLAYGROUND_CLASSIFY"),
    PLAYGROUND_EXTRACT("PLAYGROUND_EXTRACT"),
    CLASSIFY_VIA_LLM("CLASSIFY_VIA_LLM"),
    EXTRACT_VIA_LLM("EXTRACT_VIA_LLM"),
    PURCHASE_ADVICE_VIA_LLM("PURCHASE_ADVICE_VIA_LLM"),
    ASK_AND_ANALYZE("ASK_AND_ANALYZE"),
    MULTI_LEVEL_EXTRACTION("MULTI_LEVEL_EXTRACTION"),
    CLASSIFY_UPLOADED_DOCS("CLASSIFY_UPLOADED_DOCS"),
    CLASSIFY_UPLOADED_DOCS_BKP("CLASSIFY_UPLOADED_DOCS_BKP"),
    ON_LOAN_MODIFIED_RULE_EXECUTION_USING_DOC_INTEL("ON_LOAN_MODIFIED_RULE_EXECUTION_USING_DOC_INTEL"),
    EXTRACT_UPLOADED_DOCS_USING_CULMINATE("EXTRACT_UPLOADED_DOCS_USING_CULMINATE"),
    UPDATE_CUSTOM_FIELDS_FROM_UPLOADED_DOCS("update_custom_fields_from_uploaded_docs"),
    UPDATE_CUSTOM_FIELDS_FROM_SINGLE_DOC("update_custom_fields_from_single_doc"),
    SPLIT_ZIP_BAYEQUITY_CLOSING_PACKAGE("SPLIT_ZIP_BAYEQUITY_CLOSING_PACKAGE"),
    EXTRACT_DOCUMENT("EXTRACT_DOCUMENT"),
    OAK_TREE_EXTRACTION("OAK_TREE_EXTRACTION");

    private final String _type;

    RoutingTypes(String docType) {
        _type = docType;
    }

    public static RoutingTypes fromString(String text) {
        for (RoutingTypes b : RoutingTypes.values()) {
            if (b._type.equalsIgnoreCase(text)) {
                return b;
            }
        }
        return null;
    }

}
