/* =========================================================
   Extensions
   ========================================================= */
CREATE EXTENSION IF NOT EXISTS ltree;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE FUNCTION public.convert_to_jsonb(v_input text) RETURNS jsonb
    LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE
    AS $$
DECLARE v_int_value JSONB DEFAULT NULL;
BEGIN
    BEGIN
        v_int_value := to_jsonb(v_input::json);
    EXCEPTION WHEN OTHERS THEN
        v_int_value := to_jsonb(v_input);
    END;
RETURN v_int_value;
END;
$$;


ALTER FUNCTION public.convert_to_jsonb(v_input text) OWNER TO postgres;

--
-- Name: try_cast(text, anyelement); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.try_cast(_in text, INOUT _out anyelement) RETURNS anyelement
    LANGUAGE plpgsql
    AS $_$
BEGIN
   EXECUTE format('SELECT %L::%s', $1, pg_typeof(_out))
   INTO  _out;
EXCEPTION WHEN others THEN
   -- do nothing: _out already carries default
END
$_$;


ALTER FUNCTION public.try_cast(_in text, INOUT _out anyelement) OWNER TO postgres;


/* =========================================================
   System Of Records
   ========================================================= */
CREATE TABLE public."System_Of_Records" (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_of_record_name VARCHAR(255),
    metadata TEXT,
    is_active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    last_updated_at TIMESTAMP NOT NULL,
    last_updated_by VARCHAR(255)
);

/* =========================================================
   Tenant
   ========================================================= */
CREATE TABLE public."Tenant" (
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sor_id INT4 NOT NULL,
    doc_classifier_id INT4 NOT NULL,
    tenant_name VARCHAR(255),
    is_active BOOLEAN NOT NULL,
    doc_classifier_metadata TEXT,
    sor_metadata TEXT,
    created_date TIMESTAMP NOT NULL,
    last_updated_date TIMESTAMP NOT NULL,
    archived_time TIMESTAMP,
    is_archived BOOLEAN NOT NULL,
    created_by VARCHAR(255),
    last_updated_by VARCHAR(255),
    pipeline_request TEXT,
    connection_status TEXT,
    rule_strategy TEXT,
    email TEXT,
    enhanced_condition_type VARCHAR(255),
    send_loan_summary BOOLEAN DEFAULT FALSE,
    CONSTRAINT fk_tenant_sor
        FOREIGN KEY (sor_id)
        REFERENCES "System_Of_Records"(id)
);

/* =========================================================
   Tenant Settings
   ========================================================= */
CREATE TABLE tenant_settings (
    id SERIAL PRIMARY KEY,
    category VARCHAR(255) NOT NULL,
    meta JSON,
    strategy VARCHAR(255) NOT NULL,
    tenant_id INT8,
    CONSTRAINT uk_tenant_settings
        UNIQUE (category, strategy, tenant_id),
    CONSTRAINT fk_tenant_settings_tenant
        FOREIGN KEY (tenant_id)
        REFERENCES "Tenant"(id)
);

CREATE TABLE client (
	client_id uuid NOT NULL,
	address_line1 varchar(255) NULL,
	address_line2 varchar(255) NULL,
	admin_comments varchar(255) NULL,
	city varchar(255) NULL,
	client_name varchar(255) NULL,
	company_name varchar(255) NULL,
	created_at timestamp NULL,
	created_by varchar(255) NULL,
	currency varchar(255) NULL,
	email varchar(255) NULL,
	is_active bool NULL,
	last_updated_at timestamp NULL,
	last_updated_by varchar(255) NULL,
	phone_number varchar(255) NULL,
	state varchar(255) NULL,
	zipcode varchar(255) NULL,
	CONSTRAINT client_pkey PRIMARY KEY (client_id)
);

/* =========================================================
   Task Core
   ========================================================= */
CREATE TABLE task (
    topic VARCHAR(250) NOT NULL,
    sequence BIGSERIAL NOT NULL,
    identifier VARCHAR(500) NOT NULL,
    state NUMERIC(1) NOT NULL DEFAULT 1,
    descent NUMERIC(1) NOT NULL DEFAULT 1,
    owner VARCHAR(250),
    created TIMESTAMP NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    input TEXT,
    output TEXT,
    completed TIMESTAMP,
    reference VARCHAR(500),
    input_json JSONB GENERATED ALWAYS AS (convert_to_jsonb(input)) STORED,
    CONSTRAINT task_pk PRIMARY KEY (topic, sequence),
    CONSTRAINT task_state_check CHECK (state BETWEEN 0 AND 8),
    CONSTRAINT task_descent_check CHECK (descent BETWEEN 1 AND 6)
);

/* =========================================================
   Task Routes
   ========================================================= */
CREATE TABLE task_routes (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255),
    config JSONB
);

/* =========================================================
   Task Topic
   ========================================================= */
CREATE TABLE task_topic (
    topic VARCHAR(250) PRIMARY KEY
);

/* =========================================================
   Task Tree
   ========================================================= */
CREATE TABLE task_tree (
    id BIGSERIAL PRIMARY KEY,
    qualifier TEXT NOT NULL,
    levels LTREE,
    meta JSONB,
    created_at TIMESTAMPTZ,
    CONSTRAINT uk_task_tree UNIQUE (qualifier, levels)
);

/* =========================================================
   Change Ledger
   ========================================================= */
CREATE TABLE change_ledger (
    id BIGSERIAL PRIMARY KEY,
    tenant_id BIGINT,
    created_at VARCHAR(255),
    event_id VARCHAR(255),
    event_time VARCHAR(255),
    loan_identifier VARCHAR(255),
    event_type VARCHAR(255),
    logs VARCHAR(255),
    loan_number VARCHAR(255),
    flow_name VARCHAR(255),
    thread_id JSONB,
    doc_meta_data jsonb NULL,
    doc_qualifier json NULL,
    CONSTRAINT fk_change_ledger_tenant
        FOREIGN KEY (tenant_id)
        REFERENCES "Tenant"(id),
    CONSTRAINT uk_change_ledger
        UNIQUE (loan_number, flow_name, event_type, thread_id)
);

/* =========================================================
   Approval Disclosure
   ========================================================= */
CREATE TABLE approval_disclosure (
    id SERIAL PRIMARY KEY,
    loan_number VARCHAR(255),
    tenant_id INT8 NOT NULL,
    status VARCHAR(50),
    created_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    last_modified_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    loan_folder VARCHAR(255),
    flow_name VARCHAR(255),
    CONSTRAINT fk_approval_disclosure_tenant
        FOREIGN KEY (tenant_id)
        REFERENCES "Tenant"(id)
);

/* =========================================================
   User Config
   ========================================================= */
CREATE TABLE user_config (
    user_config_id UUID PRIMARY KEY,
    config_value TEXT,
    client_id UUID,
    feature_config_id UUID
);

/* =========================================================
   Notifications
   ========================================================= */
CREATE TABLE notifications (
    id SERIAL PRIMARY KEY,
    task_sequence BIGINT NOT NULL,
    status VARCHAR NOT NULL,
    created_at TIMESTAMP,
    last_updated_at TIMESTAMP,
    delivered_at TIMESTAMP,
    request_id VARCHAR
);

/* =========================================================
   Loan Notes
   ========================================================= */
CREATE TABLE loan_notes (
    id SERIAL PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    loan_guid VARCHAR(255) NOT NULL,
    notes JSONB,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    last_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_loan_notes_tenant
        FOREIGN KEY (tenant_id)
        REFERENCES "Tenant"(id)
);

CREATE TABLE public.user_filter_preferences (
	id bigserial NOT NULL,
	lo_email varchar(255) NOT NULL,
	user_preference_details jsonb NULL,
	created_at timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
	last_updated_at timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT user_filter_preferences_lo_email_key UNIQUE (lo_email),
	CONSTRAINT user_filter_preferences_pkey PRIMARY KEY (id)
);

--
-- Name: task_pretty; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.task_pretty AS
 SELECT topic,
    sequence,
    identifier,
    created,
    completed,
        CASE
            WHEN (state = (0)::numeric) THEN 'ACTIVE'::text
            WHEN (state = (1)::numeric) THEN 'READY'::text
            WHEN (state = (2)::numeric) THEN 'EXPIRED'::text
            WHEN (state = (3)::numeric) THEN 'FAILED'::text
            WHEN (state = (4)::numeric) THEN 'SUSPENDED'::text
            WHEN (state = (5)::numeric) THEN 'FILTERED'::text
            WHEN (state = (6)::numeric) THEN 'SUCCEEDED'::text
            WHEN (state = (8)::numeric) THEN 'REDUNDANT'::text
            WHEN (descent = (3)::numeric) THEN 'FAILED'::text
            WHEN (descent = (4)::numeric) THEN 'SUSPENDED'::text
            WHEN (descent = (5)::numeric) THEN 'FILTERED'::text
            WHEN (descent = (6)::numeric) THEN 'SUCCEEDED'::text
            ELSE ((('unexpected value: '::text || state) || ' with descent of '::text) || descent)
        END AS state,
        CASE
            WHEN (state = (8)::numeric) THEN 'YES'::text
            ELSE 'NO'::text
        END AS recreated,
    input,
    output,
    input_json
   FROM public.task;


ALTER VIEW public.task_pretty OWNER TO postgres;

CREATE TABLE public.task_owner (
	"owner" varchar(250) NOT NULL,
	heartbeat timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text),
	CONSTRAINT "TASK_OWNER_pkey" PRIMARY KEY (owner)
);
CREATE INDEX task_owner_idx ON public.task_owner USING btree (heartbeat);
