/* =========================================================
   Extensions
   ========================================================= */
CREATE EXTENSION IF NOT EXISTS ltree;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE system_Of_Records (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	system_of_record_name varchar(255) NULL,
	metadata text NULL,
	is_active bool NOT NULL,
	created_at timestamp NOT NULL,
	created_by varchar(255) NULL,
	last_updated_at timestamp NOT NULL,
	last_updated_by varchar(255) NULL,
	CONSTRAINT "PK_System_Of_Records" PRIMARY KEY (id)
);

/* =========================================================
   Tenant
   ========================================================= */
CREATE TABLE tenant (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	sor_id int4 NOT NULL,
	doc_classifier_id int4 NOT NULL,
	tenant_name varchar(255) NULL,
	is_active bool NOT NULL,
	doc_classifier_metadata text NULL,
	sor_metadata text NULL,
	created_date timestamp NOT NULL,
	last_updated_date timestamp NOT NULL,
	archived_time timestamp NULL,
	is_archived bool NOT NULL,
	created_by varchar(255) NULL,
	last_updated_by varchar(255) NULL,
	pipeline_request text NULL,
	connection_status text NULL,
	rule_strategy text NULL,
	email text NULL,
	enhanced_condition_type varchar(255) NULL,
	send_loan_summary bool NULL DEFAULT false,
	CONSTRAINT "PK_Tenant" PRIMARY KEY (id),
	CONSTRAINT "FK_Tenant_System_Of_Records_sor_id" FOREIGN KEY (sor_id) REFERENCES public."System_Of_Records"(id)
);

/* =========================================================
   Tenant Settings
   ========================================================= */
CREATE TABLE tenant_settings (
	id serial4 NOT NULL,
	category varchar(255) NOT NULL,
	meta json NULL,
	strategy varchar(255) NOT NULL,
	tenant_id int8 NULL,
	CONSTRAINT tenant_settings_pkey PRIMARY KEY (id),
	CONSTRAINT unique_category_strategy_tenant_id UNIQUE (category, strategy, tenant_id),
	CONSTRAINT fk_tenant_settings_tenant FOREIGN KEY (tenant_id) REFERENCES public."Tenant"(id)
);

/* =========================================================
   Task Core
   ========================================================= */
CREATE TABLE task (
	topic varchar(250) NOT NULL,
	"sequence" bigserial NOT NULL,
	identifier varchar(500) NOT NULL,
	state numeric(1) NOT NULL DEFAULT 1,
	descent numeric(1) NOT NULL DEFAULT 1,
	"owner" varchar(250) NULL,
	created timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'::text),
	"input" text NULL,
	"output" text NULL,
	completed timestamp NULL,
	reference varchar(500) NULL,
	input_json jsonb NULL GENERATED ALWAYS AS (convert_to_jsonb(input)) STORED,
	CONSTRAINT task_descent_check CHECK (((descent >= (1)::numeric) AND (descent <= (6)::numeric))),
	CONSTRAINT task_pk PRIMARY KEY (topic, sequence),
	CONSTRAINT task_state_check CHECK (((state >= (0)::numeric) AND (state <= (8)::numeric)))
);


CREATE TABLE task_routes (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255),
    config JSONB
);

CREATE TABLE task_topic (
    topic VARCHAR(250) PRIMARY KEY
);

/* =========================================================
   Task Tree
   ========================================================= */
CREATE TABLE task_tree (
    id BIGSERIAL PRIMARY KEY,
    qualifier TEXT NOT NULL,
    levels LTREE,
    meta JSONB,
    created_at TIMESTAMPTZ,
    CONSTRAINT unique_task_tree UNIQUE (qualifier, levels)
);

/* =========================================================
   Change Ledger
   ========================================================= */
CREATE TABLE change_ledger (
    id BIGSERIAL PRIMARY KEY,
    tenant_id BIGINT,
    created_at VARCHAR(255),
    event_id VARCHAR(255),
    event_time VARCHAR(255),
    loan_identifier VARCHAR(255),
    event_type VARCHAR(255),
    logs VARCHAR(255),
    loan_number VARCHAR(255),
    flow_name VARCHAR(255),
    thread_id JSONB,
    CONSTRAINT fk_change_ledger_tenant
        FOREIGN KEY (tenant_id)
        REFERENCES "Tenant"(id),
    CONSTRAINT uniq_change_ledger_threads
        UNIQUE (loan_number, flow_name, event_type, thread_id)
);

CREATE TABLE public.approval_disclosure (
	id serial4 NOT NULL,
	loan_number varchar(255) NULL,
	tenant_id int8 NOT NULL,
	status varchar(50) NULL,
	created_date timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
	last_modified_date timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
	loan_folder varchar(255) NULL,
	flow_name varchar(255) NULL,
	CONSTRAINT approval_disc_id PRIMARY KEY (id),
	CONSTRAINT fk_approval_disclosure_tenant FOREIGN KEY (tenant_id) REFERENCES public."Tenant"(id)
);

/* =========================================================
   User Config
   ========================================================= */
CREATE TABLE user_config (
    user_config_id UUID PRIMARY KEY,
    config_value TEXT,
    client_id UUID,
    feature_config_id UUID
);

/* =========================================================
   Notifications
   ========================================================= */
CREATE TABLE notifications (
    id SERIAL PRIMARY KEY,
    task_sequence BIGINT NOT NULL,
    status VARCHAR NOT NULL,
    created_at TIMESTAMP,
    last_updated_at TIMESTAMP,
    delivered_at TIMESTAMP,
    request_id VARCHAR
);

/* =========================================================
   Loan Notes
   ========================================================= */
CREATE TABLE loan_notes (
    id SERIAL PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    loan_guid VARCHAR(255) NOT NULL,
    notes JSONB,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    last_updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_loan_notes_tenant
        FOREIGN KEY (tenant_id)
        REFERENCES "Tenant"(id)
);
