--
-- PostgreSQL database dump
--
-- Dumped from database version 15.7
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Application_Config; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Application_Config" (
    id integer NOT NULL,
    type text,
    label text,
    value text NOT NULL,
    sort_position integer NOT NULL,
    field_param text,
    default_value integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by text,
    last_updated_at timestamp with time zone NOT NULL,
    last_updated_by text
);


ALTER TABLE public."Application_Config" OWNER TO postgres;

--
-- Name: Application_Config_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Application_Config" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Application_Config_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Classifier_Vallia_Field_Mappings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Classifier_Vallia_Field_Mappings" (
    id integer NOT NULL,
    classifier_field_id integer NOT NULL,
    vallia_field_id integer NOT NULL
);


ALTER TABLE public."Classifier_Vallia_Field_Mappings" OWNER TO postgres;

--
-- Name: Classifier_Vallia_Field_Mappings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Classifier_Vallia_Field_Mappings" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Classifier_Vallia_Field_Mappings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Criteria_Options; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Criteria_Options" (
    id uuid NOT NULL,
    criteria_type_id uuid NOT NULL,
    criteria_option_name character varying(255),
    sor_criteria_option_field_value character varying(255),
    created_at timestamp with time zone,
    last_updated_at timestamp with time zone,
    created_by text,
    last_updated_by text
);


ALTER TABLE public."Criteria_Options" OWNER TO postgres;

--
-- Name: Criteria_Types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Criteria_Types" (
    id uuid NOT NULL,
    criteria_name character varying(255),
    sor_field_id character varying(255),
    created_at timestamp with time zone,
    last_updated_at timestamp with time zone,
    created_by text,
    last_updated_by text
);


ALTER TABLE public."Criteria_Types" OWNER TO postgres;

--
-- Name: Doc_Classifier_Document_Categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Doc_Classifier_Document_Categories" (
    id integer NOT NULL,
    category_name text,
    vallia_doc_category_id integer NOT NULL,
    doc_classifier_id integer NOT NULL,
    created_at timestamp with time zone,
    last_updated_at timestamp with time zone,
    created_by text,
    last_updated_by text
);


ALTER TABLE public."Doc_Classifier_Document_Categories" OWNER TO postgres;

--
-- Name: Doc_Classifier_Document_Categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Doc_Classifier_Document_Categories" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Doc_Classifier_Document_Categories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Doc_Classifier_Documents; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Doc_Classifier_Documents" (
    id integer NOT NULL,
    document_name text,
    document_category_id integer NOT NULL,
    vallia_document_id integer NOT NULL,
    created_at timestamp with time zone,
    last_updated_at timestamp with time zone,
    created_by text,
    last_updated_by text
);


ALTER TABLE public."Doc_Classifier_Documents" OWNER TO postgres;

--
-- Name: Doc_Classifier_Documents_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Doc_Classifier_Documents" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Doc_Classifier_Documents_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Doc_Classifier_Fields; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Doc_Classifier_Fields" (
    id integer NOT NULL,
    field_name text,
    doc_classifier_document_id integer NOT NULL,
    created_at timestamp with time zone,
    last_updated_at timestamp with time zone,
    created_by text,
    last_updated_by text
);


ALTER TABLE public."Doc_Classifier_Fields" OWNER TO postgres;

--
-- Name: Doc_Classifier_Fields_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Doc_Classifier_Fields" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Doc_Classifier_Fields_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Doc_Classifiers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Doc_Classifiers" (
    id integer NOT NULL,
    doc_classifier_name text,
    is_active boolean NOT NULL,
    metadata text,
    created_at timestamp with time zone,
    last_updated_at timestamp with time zone,
    created_by text,
    last_updated_by text
);


ALTER TABLE public."Doc_Classifiers" OWNER TO postgres;

--
-- Name: Doc_Classifiers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Doc_Classifiers" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Doc_Classifiers_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Document_Extraction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Document_Extraction" (
    id integer NOT NULL,
    document_type character varying(255),
    loan_number character varying(255),
    extracted_json_data text,
    tenant_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    last_updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_by character varying(255),
    last_updated_by character varying(255)
);


ALTER TABLE public."Document_Extraction" OWNER TO postgres;

--
-- Name: Document_Processing_Results; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Document_Processing_Results" (
    id integer NOT NULL,
    operation_location text,
    status text,
    tenant_id integer NOT NULL,
    blob_folder_name text,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    total_pages integer NOT NULL,
    loan_number text,
    document_name character varying(256),
    classified_page_count integer,
    unclassified_page_count integer
);


ALTER TABLE public."Document_Processing_Results" OWNER TO postgres;

--
-- Name: Document_Processing_Results_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Document_Processing_Results" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Document_Processing_Results_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Document_Upload_Failure_Status; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Document_Upload_Failure_Status" (
    id integer NOT NULL,
    tenant_id integer NOT NULL,
    loan_guid uuid NOT NULL,
    document_id integer,
    document_title text,
    force_create_new_document boolean NOT NULL,
    attachment_title text,
    attachment_byte_array_data bytea,
    content_type text,
    attachment_title_with_file_extension text,
    status text,
    error_message text,
    date_time timestamp with time zone NOT NULL
);


ALTER TABLE public."Document_Upload_Failure_Status" OWNER TO postgres;

--
-- Name: Document_Upload_Failure_Status_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Document_Upload_Failure_Status" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Document_Upload_Failure_Status_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Field_SOT_Mappings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Field_SOT_Mappings" (
    id integer NOT NULL,
    vallia_field_id integer NOT NULL,
    is_vallia_doc_sot boolean NOT NULL,
    sor_field_id integer,
    vallia_document_id integer,
    "Tenant_Id" integer NOT NULL
);


ALTER TABLE public."Field_SOT_Mappings" OWNER TO postgres;

--
-- Name: Field_SOT_Mappings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Field_SOT_Mappings" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Field_SOT_Mappings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Flow_Batch; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Flow_Batch" (
    id integer NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    status text
);


ALTER TABLE public."Flow_Batch" OWNER TO postgres;

--
-- Name: Flow_Batch_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Flow_Batch" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Flow_Batch_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Global_Flow_Flow_Rules_Mappings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Global_Flow_Flow_Rules_Mappings" (
    flow_id uuid NOT NULL,
    flow_rule_id uuid NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public."Global_Flow_Flow_Rules_Mappings" OWNER TO postgres;

--
-- Name: Global_Flow_Rules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Global_Flow_Rules" (
    id uuid NOT NULL,
    flow_rule_name text,
    is_active boolean NOT NULL,
    trigger_event_type text,
    trigger_resource_document_id integer NOT NULL,
    rule_details text,
    rule_actions text,
    created_at timestamp with time zone,
    last_updated_at timestamp with time zone,
    created_by text,
    last_updated_by text
);


ALTER TABLE public."Global_Flow_Rules" OWNER TO postgres;

--
-- Name: Global_Flows; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Global_Flows" (
    id uuid NOT NULL,
    flow_name text,
    is_active boolean NOT NULL,
    is_default_for_new_tenants boolean NOT NULL,
    loan_milestones text,
    user_roles text,
    created_at timestamp with time zone,
    last_updated_at timestamp with time zone,
    created_by text,
    last_updated_by text,
    is_archived boolean DEFAULT false
);


ALTER TABLE public."Global_Flows" OWNER TO postgres;

--
-- Name: Loan_Batch_Job; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Loan_Batch_Job" (
    id integer NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    status text,
    success_loan_id text
);


ALTER TABLE public."Loan_Batch_Job" OWNER TO postgres;

--
-- Name: Loan_Batch_Job_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Loan_Batch_Job" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Loan_Batch_Job_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Ocrolus_Books; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Ocrolus_Books" (
    id integer NOT NULL,
    tenant_id integer NOT NULL,
    book_uuid text NOT NULL,
    book_name text NOT NULL,
    pk integer NOT NULL,
    created_ts timestamp with time zone NOT NULL,
    book_type text NOT NULL,
    book_class text NOT NULL
);


ALTER TABLE public."Ocrolus_Books" OWNER TO postgres;

--
-- Name: Ocrolus_Books_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Ocrolus_Books" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Ocrolus_Books_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Ocrolus_Documents; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Ocrolus_Documents" (
    id integer NOT NULL,
    docs_uuid text NOT NULL,
    doc_name text NOT NULL,
    page_count integer NOT NULL,
    created_ts timestamp with time zone NOT NULL,
    book_uuid text NOT NULL,
    blob_name text
);


ALTER TABLE public."Ocrolus_Documents" OWNER TO postgres;

--
-- Name: Ocrolus_Documents_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Ocrolus_Documents" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Ocrolus_Documents_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: System_Of_Record_Fields; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."System_Of_Record_Fields" (
    id integer NOT NULL,
    field_id text,
    field_name text,
    sor_id integer NOT NULL,
    tenant_id integer NOT NULL,
    is_custom_field_id boolean NOT NULL
);


ALTER TABLE public."System_Of_Record_Fields" OWNER TO postgres;

--
-- Name: System_Of_Record_Fields_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."System_Of_Record_Fields" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."System_Of_Record_Fields_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: System_Of_Records; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."System_Of_Records" (
    id integer NOT NULL,
    system_of_record_name character varying(200),
    metadata text,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by character varying(100),
    last_updated_at timestamp with time zone NOT NULL,
    last_updated_by character varying(100)
);


ALTER TABLE public."System_Of_Records" OWNER TO postgres;

--
-- Name: System_Of_Records_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."System_Of_Records" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."System_Of_Records_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: System_of_Record_Folders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."System_of_Record_Folders" (
    id integer NOT NULL,
    folder_name character varying(200),
    sor_folder_id text,
    is_listened_by_vallia_doc_flow boolean NOT NULL,
    tenant_id integer NOT NULL,
    created_at timestamp with time zone,
    last_updated_at timestamp with time zone,
    created_by text,
    last_updated_by text
);


ALTER TABLE public."System_of_Record_Folders" OWNER TO postgres;

--
-- Name: System_of_Record_Folders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."System_of_Record_Folders" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."System_of_Record_Folders_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Tenant; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tenant" (
    id integer NOT NULL,
    sor_id integer NOT NULL,
    doc_classifier_id integer NOT NULL,
    tenant_name character varying(200),
    is_active boolean NOT NULL,
    doc_classifier_metadata text,
    sor_metadata text,
    created_date timestamp with time zone NOT NULL,
    last_updated_date timestamp with time zone NOT NULL,
    archived_time timestamp with time zone,
    is_archived boolean NOT NULL,
    created_by character varying(100),
    last_updated_by character varying(100),
    pipeline_request text,
    connection_status text
);


ALTER TABLE public."Tenant" OWNER TO postgres;

--
-- Name: Tenant_Connections; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tenant_Connections" (
    connection_tracking_id uuid NOT NULL,
    tenant_id integer NOT NULL,
    connected_at timestamp with time zone NOT NULL,
    connected_by text,
    connection_status text,
    browser text,
    display_resolution text,
    operating_system text,
    encrypted_sor_token text,
    created_at timestamp with time zone,
    last_updated_at timestamp with time zone,
    created_by text,
    last_updated_by text
);


ALTER TABLE public."Tenant_Connections" OWNER TO postgres;

--
-- Name: Tenant_Flow_Rules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tenant_Flow_Rules" (
    id uuid NOT NULL,
    flow_rule_name text,
    is_active boolean NOT NULL,
    trigger_event_type text,
    trigger_resource_document_id integer NOT NULL,
    tenant_flow_id uuid NOT NULL,
    rule_details text,
    rule_actions text,
    global_flow_rule_id uuid NOT NULL,
    created_at timestamp with time zone,
    last_updated_at timestamp with time zone,
    created_by text,
    last_updated_by text
);


ALTER TABLE public."Tenant_Flow_Rules" OWNER TO postgres;

--
-- Name: Tenant_Flow_Rules_Activities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tenant_Flow_Rules_Activities" (
    id uuid NOT NULL,
    flow_rule_activity_name text,
    flow_rule_id uuid NOT NULL,
    document_id text,
    document_name text,
    attachment_id text,
    loan_number text,
    type text,
    status text,
    created_date timestamp with time zone NOT NULL,
    modified_date timestamp with time zone NOT NULL,
    tenant_flow_activity_id uuid NOT NULL,
    ocrolus_doc_uuid text,
    rule_result text,
    blob_folder_name text
);


ALTER TABLE public."Tenant_Flow_Rules_Activities" OWNER TO postgres;

--
-- Name: Tenant_Flows; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tenant_Flows" (
    id uuid NOT NULL,
    tenant_id integer NOT NULL,
    global_flow_id uuid NOT NULL,
    flow_name text,
    is_active boolean NOT NULL,
    loan_milestones text,
    user_roles text,
    created_at timestamp with time zone,
    last_updated_at timestamp with time zone,
    created_by text,
    last_updated_by text,
    is_archived boolean DEFAULT false,
    is_global_flow boolean NOT NULL
);


ALTER TABLE public."Tenant_Flows" OWNER TO postgres;

--
-- Name: Tenant_Flows_Activities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Tenant_Flows_Activities" (
    id uuid NOT NULL,
    tenant_flow_id uuid NOT NULL,
    loan_number text,
    status text,
    start_date timestamp with time zone NOT NULL,
    completed_date timestamp with time zone,
    borrower_name text
);


ALTER TABLE public."Tenant_Flows_Activities" OWNER TO postgres;

--
-- Name: Tenant_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Tenant" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tenant_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Vallia_Document_Categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Vallia_Document_Categories" (
    id integer NOT NULL,
    category_name text,
    is_all_documents_mapped boolean NOT NULL,
    created_at timestamp with time zone,
    last_updated_at timestamp with time zone,
    created_by text,
    last_updated_by text
);


ALTER TABLE public."Vallia_Document_Categories" OWNER TO postgres;

--
-- Name: Vallia_Document_Categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Vallia_Document_Categories" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Vallia_Document_Categories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Vallia_Documents; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Vallia_Documents" (
    id integer NOT NULL,
    document_name text,
    document_category_id integer NOT NULL,
    created_at timestamp with time zone,
    last_updated_at timestamp with time zone,
    created_by text,
    last_updated_by text
);


ALTER TABLE public."Vallia_Documents" OWNER TO postgres;

--
-- Name: Vallia_Documents_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Vallia_Documents" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Vallia_Documents_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Vallia_Fields; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Vallia_Fields" (
    id integer NOT NULL,
    field_name text,
    data_type text,
    created_at timestamp with time zone,
    last_updated_at timestamp with time zone,
    created_by text,
    last_updated_by text
);


ALTER TABLE public."Vallia_Fields" OWNER TO postgres;

--
-- Name: Vallia_Fields_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Vallia_Fields" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Vallia_Fields_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Vallia_Sor_Document_Mappings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Vallia_Sor_Document_Mappings" (
    id integer NOT NULL,
    vallia_document_id integer NOT NULL,
    sor_folder_id integer NOT NULL,
    is_active boolean DEFAULT true NOT NULL
);


ALTER TABLE public."Vallia_Sor_Document_Mappings" OWNER TO postgres;

--
-- Name: Vallia_Sor_Document_Mappings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Vallia_Sor_Document_Mappings" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Vallia_Sor_Document_Mappings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Vallia_Sor_Field_Mappings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Vallia_Sor_Field_Mappings" (
    id integer NOT NULL,
    sor_field_id integer NOT NULL,
    vallia_field_id integer NOT NULL,
    is_active boolean DEFAULT true NOT NULL
);


ALTER TABLE public."Vallia_Sor_Field_Mappings" OWNER TO postgres;

--
-- Name: Vallia_Sor_Field_Mappings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Vallia_Sor_Field_Mappings" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Vallia_Sor_Field_Mappings_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Name: document_extraction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.document_extraction_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.document_extraction_id_seq OWNER TO postgres;

--
-- Name: document_extraction_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.document_extraction_id_seq OWNED BY public."Document_Extraction".id;


--
-- Name: Document_Extraction id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Document_Extraction" ALTER COLUMN id SET DEFAULT nextval('public.document_extraction_id_seq'::regclass);


--
-- Name: Ocrolus_Books AK_Ocrolus_Books_book_uuid; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Ocrolus_Books"
    ADD CONSTRAINT "AK_Ocrolus_Books_book_uuid" UNIQUE (book_uuid);


--
-- Name: Application_Config PK_Application_Config; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Application_Config"
    ADD CONSTRAINT "PK_Application_Config" PRIMARY KEY (id);


--
-- Name: Classifier_Vallia_Field_Mappings PK_Classifier_Vallia_Field_Mappings; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Classifier_Vallia_Field_Mappings"
    ADD CONSTRAINT "PK_Classifier_Vallia_Field_Mappings" PRIMARY KEY (id);


--
-- Name: Criteria_Options PK_Criteria_Options; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Criteria_Options"
    ADD CONSTRAINT "PK_Criteria_Options" PRIMARY KEY (id);


--
-- Name: Criteria_Types PK_Criteria_Types; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Criteria_Types"
    ADD CONSTRAINT "PK_Criteria_Types" PRIMARY KEY (id);


--
-- Name: Doc_Classifier_Document_Categories PK_Doc_Classifier_Document_Categories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Doc_Classifier_Document_Categories"
    ADD CONSTRAINT "PK_Doc_Classifier_Document_Categories" PRIMARY KEY (id);


--
-- Name: Doc_Classifier_Documents PK_Doc_Classifier_Documents; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Doc_Classifier_Documents"
    ADD CONSTRAINT "PK_Doc_Classifier_Documents" PRIMARY KEY (id);


--
-- Name: Doc_Classifier_Fields PK_Doc_Classifier_Fields; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Doc_Classifier_Fields"
    ADD CONSTRAINT "PK_Doc_Classifier_Fields" PRIMARY KEY (id);


--
-- Name: Doc_Classifiers PK_Doc_Classifiers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Doc_Classifiers"
    ADD CONSTRAINT "PK_Doc_Classifiers" PRIMARY KEY (id);


--
-- Name: Document_Processing_Results PK_Document_Processing_Results; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Document_Processing_Results"
    ADD CONSTRAINT "PK_Document_Processing_Results" PRIMARY KEY (id);


--
-- Name: Document_Upload_Failure_Status PK_Document_Upload_Failure_Status; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Document_Upload_Failure_Status"
    ADD CONSTRAINT "PK_Document_Upload_Failure_Status" PRIMARY KEY (id);


--
-- Name: Field_SOT_Mappings PK_Field_SOT_Mappings; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Field_SOT_Mappings"
    ADD CONSTRAINT "PK_Field_SOT_Mappings" PRIMARY KEY (id);


--
-- Name: Flow_Batch PK_Flow_Batch; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Flow_Batch"
    ADD CONSTRAINT "PK_Flow_Batch" PRIMARY KEY (id);


--
-- Name: Global_Flow_Flow_Rules_Mappings PK_Global_Flow_Flow_Rules_Mappings; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Global_Flow_Flow_Rules_Mappings"
    ADD CONSTRAINT "PK_Global_Flow_Flow_Rules_Mappings" PRIMARY KEY (flow_id, flow_rule_id);


--
-- Name: Global_Flow_Rules PK_Global_Flow_Rules; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Global_Flow_Rules"
    ADD CONSTRAINT "PK_Global_Flow_Rules" PRIMARY KEY (id);


--
-- Name: Global_Flows PK_Global_Flows; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Global_Flows"
    ADD CONSTRAINT "PK_Global_Flows" PRIMARY KEY (id);


--
-- Name: Loan_Batch_Job PK_Loan_Batch_Job; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Loan_Batch_Job"
    ADD CONSTRAINT "PK_Loan_Batch_Job" PRIMARY KEY (id);


--
-- Name: Ocrolus_Books PK_Ocrolus_Books; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Ocrolus_Books"
    ADD CONSTRAINT "PK_Ocrolus_Books" PRIMARY KEY (id);


--
-- Name: Ocrolus_Documents PK_Ocrolus_Documents; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Ocrolus_Documents"
    ADD CONSTRAINT "PK_Ocrolus_Documents" PRIMARY KEY (id);


--
-- Name: System_Of_Record_Fields PK_System_Of_Record_Fields; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."System_Of_Record_Fields"
    ADD CONSTRAINT "PK_System_Of_Record_Fields" PRIMARY KEY (id);


--
-- Name: System_Of_Records PK_System_Of_Records; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."System_Of_Records"
    ADD CONSTRAINT "PK_System_Of_Records" PRIMARY KEY (id);


--
-- Name: System_of_Record_Folders PK_System_of_Record_Folders; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."System_of_Record_Folders"
    ADD CONSTRAINT "PK_System_of_Record_Folders" PRIMARY KEY (id);


--
-- Name: Tenant PK_Tenant; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tenant"
    ADD CONSTRAINT "PK_Tenant" PRIMARY KEY (id);


--
-- Name: Tenant_Connections PK_Tenant_Connections; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tenant_Connections"
    ADD CONSTRAINT "PK_Tenant_Connections" PRIMARY KEY (connection_tracking_id);


--
-- Name: Tenant_Flow_Rules PK_Tenant_Flow_Rules; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tenant_Flow_Rules"
    ADD CONSTRAINT "PK_Tenant_Flow_Rules" PRIMARY KEY (id);


--
-- Name: Tenant_Flow_Rules_Activities PK_Tenant_Flow_Rules_Activities; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tenant_Flow_Rules_Activities"
    ADD CONSTRAINT "PK_Tenant_Flow_Rules_Activities" PRIMARY KEY (id);


--
-- Name: Tenant_Flows PK_Tenant_Flows; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tenant_Flows"
    ADD CONSTRAINT "PK_Tenant_Flows" PRIMARY KEY (id);


--
-- Name: Tenant_Flows_Activities PK_Tenant_Flows_Activities; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tenant_Flows_Activities"
    ADD CONSTRAINT "PK_Tenant_Flows_Activities" PRIMARY KEY (id);


--
-- Name: Vallia_Document_Categories PK_Vallia_Document_Categories; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Vallia_Document_Categories"
    ADD CONSTRAINT "PK_Vallia_Document_Categories" PRIMARY KEY (id);


--
-- Name: Vallia_Documents PK_Vallia_Documents; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Vallia_Documents"
    ADD CONSTRAINT "PK_Vallia_Documents" PRIMARY KEY (id);


--
-- Name: Vallia_Fields PK_Vallia_Fields; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Vallia_Fields"
    ADD CONSTRAINT "PK_Vallia_Fields" PRIMARY KEY (id);


--
-- Name: Vallia_Sor_Document_Mappings PK_Vallia_Sor_Document_Mappings; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Vallia_Sor_Document_Mappings"
    ADD CONSTRAINT "PK_Vallia_Sor_Document_Mappings" PRIMARY KEY (id);


--
-- Name: Vallia_Sor_Field_Mappings PK_Vallia_Sor_Field_Mappings; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Vallia_Sor_Field_Mappings"
    ADD CONSTRAINT "PK_Vallia_Sor_Field_Mappings" PRIMARY KEY (id);


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: Document_Extraction document_extraction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Document_Extraction"
    ADD CONSTRAINT document_extraction_pkey PRIMARY KEY (id);


--
-- Name: IX_Classifier_Vallia_Field_Mappings_classifier_field_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Classifier_Vallia_Field_Mappings_classifier_field_id" ON public."Classifier_Vallia_Field_Mappings" USING btree (classifier_field_id);


--
-- Name: IX_Classifier_Vallia_Field_Mappings_vallia_field_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Classifier_Vallia_Field_Mappings_vallia_field_id" ON public."Classifier_Vallia_Field_Mappings" USING btree (vallia_field_id);


--
-- Name: IX_Criteria_Options_criteria_type_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Criteria_Options_criteria_type_id" ON public."Criteria_Options" USING btree (criteria_type_id);


--
-- Name: IX_Doc_Classifier_Document_Categories_doc_classifier_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Doc_Classifier_Document_Categories_doc_classifier_id" ON public."Doc_Classifier_Document_Categories" USING btree (doc_classifier_id);


--
-- Name: IX_Doc_Classifier_Document_Categories_vallia_doc_category_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Doc_Classifier_Document_Categories_vallia_doc_category_id" ON public."Doc_Classifier_Document_Categories" USING btree (vallia_doc_category_id);


--
-- Name: IX_Doc_Classifier_Documents_document_category_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Doc_Classifier_Documents_document_category_id" ON public."Doc_Classifier_Documents" USING btree (document_category_id);


--
-- Name: IX_Doc_Classifier_Documents_vallia_document_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Doc_Classifier_Documents_vallia_document_id" ON public."Doc_Classifier_Documents" USING btree (vallia_document_id);


--
-- Name: IX_Doc_Classifier_Fields_doc_classifier_document_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Doc_Classifier_Fields_doc_classifier_document_id" ON public."Doc_Classifier_Fields" USING btree (doc_classifier_document_id);


--
-- Name: IX_Document_Upload_Failure_Status_tenant_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Document_Upload_Failure_Status_tenant_id" ON public."Document_Upload_Failure_Status" USING btree (tenant_id);


--
-- Name: IX_Field_SOT_Mappings_Tenant_Id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Field_SOT_Mappings_Tenant_Id" ON public."Field_SOT_Mappings" USING btree ("Tenant_Id");


--
-- Name: IX_Field_SOT_Mappings_sor_field_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Field_SOT_Mappings_sor_field_id" ON public."Field_SOT_Mappings" USING btree (sor_field_id);


--
-- Name: IX_Field_SOT_Mappings_vallia_document_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Field_SOT_Mappings_vallia_document_id" ON public."Field_SOT_Mappings" USING btree (vallia_document_id);


--
-- Name: IX_Field_SOT_Mappings_vallia_field_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Field_SOT_Mappings_vallia_field_id" ON public."Field_SOT_Mappings" USING btree (vallia_field_id);


--
-- Name: IX_Global_Flow_Flow_Rules_Mappings_flow_rule_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Global_Flow_Flow_Rules_Mappings_flow_rule_id" ON public."Global_Flow_Flow_Rules_Mappings" USING btree (flow_rule_id);


--
-- Name: IX_Global_Flow_Rules_trigger_resource_document_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Global_Flow_Rules_trigger_resource_document_id" ON public."Global_Flow_Rules" USING btree (trigger_resource_document_id);


--
-- Name: IX_Ocrolus_Books_tenant_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Ocrolus_Books_tenant_id" ON public."Ocrolus_Books" USING btree (tenant_id);


--
-- Name: IX_Ocrolus_Documents_book_uuid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Ocrolus_Documents_book_uuid" ON public."Ocrolus_Documents" USING btree (book_uuid);


--
-- Name: IX_System_Of_Record_Fields_sor_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_System_Of_Record_Fields_sor_id" ON public."System_Of_Record_Fields" USING btree (sor_id);


--
-- Name: IX_System_Of_Record_Fields_tenant_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_System_Of_Record_Fields_tenant_id" ON public."System_Of_Record_Fields" USING btree (tenant_id);


--
-- Name: IX_System_of_Record_Folders_tenant_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_System_of_Record_Folders_tenant_id" ON public."System_of_Record_Folders" USING btree (tenant_id);


--
-- Name: IX_Tenant_Connections_tenant_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tenant_Connections_tenant_id" ON public."Tenant_Connections" USING btree (tenant_id);


--
-- Name: IX_Tenant_Flow_Rules_Activities_flow_rule_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tenant_Flow_Rules_Activities_flow_rule_id" ON public."Tenant_Flow_Rules_Activities" USING btree (flow_rule_id);


--
-- Name: IX_Tenant_Flow_Rules_Activities_tenant_flow_activity_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tenant_Flow_Rules_Activities_tenant_flow_activity_id" ON public."Tenant_Flow_Rules_Activities" USING btree (tenant_flow_activity_id);


--
-- Name: IX_Tenant_Flow_Rules_global_flow_rule_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tenant_Flow_Rules_global_flow_rule_id" ON public."Tenant_Flow_Rules" USING btree (global_flow_rule_id);


--
-- Name: IX_Tenant_Flow_Rules_tenant_flow_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tenant_Flow_Rules_tenant_flow_id" ON public."Tenant_Flow_Rules" USING btree (tenant_flow_id);


--
-- Name: IX_Tenant_Flow_Rules_trigger_resource_document_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tenant_Flow_Rules_trigger_resource_document_id" ON public."Tenant_Flow_Rules" USING btree (trigger_resource_document_id);


--
-- Name: IX_Tenant_Flows_Activities_tenant_flow_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tenant_Flows_Activities_tenant_flow_id" ON public."Tenant_Flows_Activities" USING btree (tenant_flow_id);


--
-- Name: IX_Tenant_Flows_global_flow_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tenant_Flows_global_flow_id" ON public."Tenant_Flows" USING btree (global_flow_id);


--
-- Name: IX_Tenant_Flows_tenant_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tenant_Flows_tenant_id" ON public."Tenant_Flows" USING btree (tenant_id);


--
-- Name: IX_Tenant_doc_classifier_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tenant_doc_classifier_id" ON public."Tenant" USING btree (doc_classifier_id);


--
-- Name: IX_Tenant_sor_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Tenant_sor_id" ON public."Tenant" USING btree (sor_id);


--
-- Name: IX_Vallia_Documents_document_category_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Vallia_Documents_document_category_id" ON public."Vallia_Documents" USING btree (document_category_id);


--
-- Name: IX_Vallia_Sor_Document_Mappings_sor_folder_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Vallia_Sor_Document_Mappings_sor_folder_id" ON public."Vallia_Sor_Document_Mappings" USING btree (sor_folder_id);


--
-- Name: IX_Vallia_Sor_Document_Mappings_vallia_document_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Vallia_Sor_Document_Mappings_vallia_document_id" ON public."Vallia_Sor_Document_Mappings" USING btree (vallia_document_id);


--
-- Name: IX_Vallia_Sor_Field_Mappings_sor_field_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Vallia_Sor_Field_Mappings_sor_field_id" ON public."Vallia_Sor_Field_Mappings" USING btree (sor_field_id);


--
-- Name: IX_Vallia_Sor_Field_Mappings_vallia_field_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Vallia_Sor_Field_Mappings_vallia_field_id" ON public."Vallia_Sor_Field_Mappings" USING btree (vallia_field_id);


--
-- Name: Classifier_Vallia_Field_Mappings FK_Classifier_Vallia_Field_Mappings_Doc_Classifier_Fields_clas~; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Classifier_Vallia_Field_Mappings"
    ADD CONSTRAINT "FK_Classifier_Vallia_Field_Mappings_Doc_Classifier_Fields_clas~" FOREIGN KEY (classifier_field_id) REFERENCES public."Doc_Classifier_Fields"(id);


--
-- Name: Classifier_Vallia_Field_Mappings FK_Classifier_Vallia_Field_Mappings_Vallia_Fields_vallia_field~; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Classifier_Vallia_Field_Mappings"
    ADD CONSTRAINT "FK_Classifier_Vallia_Field_Mappings_Vallia_Fields_vallia_field~" FOREIGN KEY (vallia_field_id) REFERENCES public."Vallia_Fields"(id);


--
-- Name: Criteria_Options FK_Criteria_Options_Criteria_Types_criteria_type_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Criteria_Options"
    ADD CONSTRAINT "FK_Criteria_Options_Criteria_Types_criteria_type_id" FOREIGN KEY (criteria_type_id) REFERENCES public."Criteria_Types"(id);


--
-- Name: Doc_Classifier_Document_Categories FK_Doc_Classifier_Document_Categories_Doc_Classifiers_doc_clas~; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Doc_Classifier_Document_Categories"
    ADD CONSTRAINT "FK_Doc_Classifier_Document_Categories_Doc_Classifiers_doc_clas~" FOREIGN KEY (doc_classifier_id) REFERENCES public."Doc_Classifiers"(id);


--
-- Name: Doc_Classifier_Document_Categories FK_Doc_Classifier_Document_Categories_Vallia_Document_Categori~; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Doc_Classifier_Document_Categories"
    ADD CONSTRAINT "FK_Doc_Classifier_Document_Categories_Vallia_Document_Categori~" FOREIGN KEY (vallia_doc_category_id) REFERENCES public."Vallia_Document_Categories"(id);


--
-- Name: Doc_Classifier_Documents FK_Doc_Classifier_Documents_Doc_Classifier_Document_Categories~; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Doc_Classifier_Documents"
    ADD CONSTRAINT "FK_Doc_Classifier_Documents_Doc_Classifier_Document_Categories~" FOREIGN KEY (document_category_id) REFERENCES public."Doc_Classifier_Document_Categories"(id);


--
-- Name: Doc_Classifier_Documents FK_Doc_Classifier_Documents_Vallia_Documents_vallia_document_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Doc_Classifier_Documents"
    ADD CONSTRAINT "FK_Doc_Classifier_Documents_Vallia_Documents_vallia_document_id" FOREIGN KEY (vallia_document_id) REFERENCES public."Vallia_Documents"(id);


--
-- Name: Doc_Classifier_Fields FK_Doc_Classifier_Fields_Doc_Classifier_Documents_doc_classifi~; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Doc_Classifier_Fields"
    ADD CONSTRAINT "FK_Doc_Classifier_Fields_Doc_Classifier_Documents_doc_classifi~" FOREIGN KEY (doc_classifier_document_id) REFERENCES public."Doc_Classifier_Documents"(id);


--
-- Name: Document_Upload_Failure_Status FK_Document_Upload_Failure_Status_Tenant_tenant_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Document_Upload_Failure_Status"
    ADD CONSTRAINT "FK_Document_Upload_Failure_Status_Tenant_tenant_id" FOREIGN KEY (tenant_id) REFERENCES public."Tenant"(id);


--
-- Name: Field_SOT_Mappings FK_Field_SOT_Mappings_System_Of_Record_Fields_sor_field_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Field_SOT_Mappings"
    ADD CONSTRAINT "FK_Field_SOT_Mappings_System_Of_Record_Fields_sor_field_id" FOREIGN KEY (sor_field_id) REFERENCES public."System_Of_Record_Fields"(id);


--
-- Name: Field_SOT_Mappings FK_Field_SOT_Mappings_Tenant_Tenant_Id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Field_SOT_Mappings"
    ADD CONSTRAINT "FK_Field_SOT_Mappings_Tenant_Tenant_Id" FOREIGN KEY ("Tenant_Id") REFERENCES public."Tenant"(id);


--
-- Name: Field_SOT_Mappings FK_Field_SOT_Mappings_Vallia_Documents_vallia_document_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Field_SOT_Mappings"
    ADD CONSTRAINT "FK_Field_SOT_Mappings_Vallia_Documents_vallia_document_id" FOREIGN KEY (vallia_document_id) REFERENCES public."Vallia_Documents"(id);


--
-- Name: Field_SOT_Mappings FK_Field_SOT_Mappings_Vallia_Fields_vallia_field_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Field_SOT_Mappings"
    ADD CONSTRAINT "FK_Field_SOT_Mappings_Vallia_Fields_vallia_field_id" FOREIGN KEY (vallia_field_id) REFERENCES public."Vallia_Fields"(id);


--
-- Name: Global_Flow_Flow_Rules_Mappings FK_Global_Flow_Flow_Rules_Mappings_Global_Flow_Rules_flow_rule~; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Global_Flow_Flow_Rules_Mappings"
    ADD CONSTRAINT "FK_Global_Flow_Flow_Rules_Mappings_Global_Flow_Rules_flow_rule~" FOREIGN KEY (flow_rule_id) REFERENCES public."Global_Flow_Rules"(id) ON DELETE CASCADE;


--
-- Name: Global_Flow_Flow_Rules_Mappings FK_Global_Flow_Flow_Rules_Mappings_Global_Flows_flow_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Global_Flow_Flow_Rules_Mappings"
    ADD CONSTRAINT "FK_Global_Flow_Flow_Rules_Mappings_Global_Flows_flow_id" FOREIGN KEY (flow_id) REFERENCES public."Global_Flows"(id) ON DELETE CASCADE;


--
-- Name: Global_Flow_Rules FK_Global_Flow_Rules_Vallia_Documents_trigger_resource_documen~; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Global_Flow_Rules"
    ADD CONSTRAINT "FK_Global_Flow_Rules_Vallia_Documents_trigger_resource_documen~" FOREIGN KEY (trigger_resource_document_id) REFERENCES public."Vallia_Documents"(id);


--
-- Name: Ocrolus_Books FK_Ocrolus_Books_Tenant_tenant_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Ocrolus_Books"
    ADD CONSTRAINT "FK_Ocrolus_Books_Tenant_tenant_id" FOREIGN KEY (tenant_id) REFERENCES public."Tenant"(id) ON DELETE CASCADE;


--
-- Name: Ocrolus_Documents FK_Ocrolus_Documents_Ocrolus_Books_book_uuid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Ocrolus_Documents"
    ADD CONSTRAINT "FK_Ocrolus_Documents_Ocrolus_Books_book_uuid" FOREIGN KEY (book_uuid) REFERENCES public."Ocrolus_Books"(book_uuid) ON DELETE CASCADE;


--
-- Name: System_Of_Record_Fields FK_System_Of_Record_Fields_System_Of_Records_sor_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."System_Of_Record_Fields"
    ADD CONSTRAINT "FK_System_Of_Record_Fields_System_Of_Records_sor_id" FOREIGN KEY (sor_id) REFERENCES public."System_Of_Records"(id);


--
-- Name: System_Of_Record_Fields FK_System_Of_Record_Fields_Tenant_tenant_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."System_Of_Record_Fields"
    ADD CONSTRAINT "FK_System_Of_Record_Fields_Tenant_tenant_id" FOREIGN KEY (tenant_id) REFERENCES public."Tenant"(id);


--
-- Name: System_of_Record_Folders FK_System_of_Record_Folders_Tenant_tenant_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."System_of_Record_Folders"
    ADD CONSTRAINT "FK_System_of_Record_Folders_Tenant_tenant_id" FOREIGN KEY (tenant_id) REFERENCES public."Tenant"(id);


--
-- Name: Tenant_Connections FK_Tenant_Connections_Tenant_tenant_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tenant_Connections"
    ADD CONSTRAINT "FK_Tenant_Connections_Tenant_tenant_id" FOREIGN KEY (tenant_id) REFERENCES public."Tenant"(id);


--
-- Name: Tenant FK_Tenant_Doc_Classifiers_doc_classifier_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tenant"
    ADD CONSTRAINT "FK_Tenant_Doc_Classifiers_doc_classifier_id" FOREIGN KEY (doc_classifier_id) REFERENCES public."Doc_Classifiers"(id);


--
-- Name: Tenant_Flow_Rules_Activities FK_Tenant_Flow_Rules_Activities_Tenant_Flow_Rules_flow_rule_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tenant_Flow_Rules_Activities"
    ADD CONSTRAINT "FK_Tenant_Flow_Rules_Activities_Tenant_Flow_Rules_flow_rule_id" FOREIGN KEY (flow_rule_id) REFERENCES public."Tenant_Flow_Rules"(id);


--
-- Name: Tenant_Flow_Rules_Activities FK_Tenant_Flow_Rules_Activities_Tenant_Flows_Activities_tenant~; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tenant_Flow_Rules_Activities"
    ADD CONSTRAINT "FK_Tenant_Flow_Rules_Activities_Tenant_Flows_Activities_tenant~" FOREIGN KEY (tenant_flow_activity_id) REFERENCES public."Tenant_Flows_Activities"(id);


--
-- Name: Tenant_Flow_Rules FK_Tenant_Flow_Rules_Global_Flow_Rules_global_flow_rule_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tenant_Flow_Rules"
    ADD CONSTRAINT "FK_Tenant_Flow_Rules_Global_Flow_Rules_global_flow_rule_id" FOREIGN KEY (global_flow_rule_id) REFERENCES public."Global_Flow_Rules"(id);


--
-- Name: Tenant_Flow_Rules FK_Tenant_Flow_Rules_Tenant_Flows_tenant_flow_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tenant_Flow_Rules"
    ADD CONSTRAINT "FK_Tenant_Flow_Rules_Tenant_Flows_tenant_flow_id" FOREIGN KEY (tenant_flow_id) REFERENCES public."Tenant_Flows"(id);


--
-- Name: Tenant_Flow_Rules FK_Tenant_Flow_Rules_Vallia_Documents_trigger_resource_documen~; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tenant_Flow_Rules"
    ADD CONSTRAINT "FK_Tenant_Flow_Rules_Vallia_Documents_trigger_resource_documen~" FOREIGN KEY (trigger_resource_document_id) REFERENCES public."Vallia_Documents"(id);


--
-- Name: Tenant_Flows_Activities FK_Tenant_Flows_Activities_Tenant_Flows_tenant_flow_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tenant_Flows_Activities"
    ADD CONSTRAINT "FK_Tenant_Flows_Activities_Tenant_Flows_tenant_flow_id" FOREIGN KEY (tenant_flow_id) REFERENCES public."Tenant_Flows"(id);


--
-- Name: Tenant_Flows FK_Tenant_Flows_Global_Flows_global_flow_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tenant_Flows"
    ADD CONSTRAINT "FK_Tenant_Flows_Global_Flows_global_flow_id" FOREIGN KEY (global_flow_id) REFERENCES public."Global_Flows"(id);


--
-- Name: Tenant_Flows FK_Tenant_Flows_Tenant_tenant_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tenant_Flows"
    ADD CONSTRAINT "FK_Tenant_Flows_Tenant_tenant_id" FOREIGN KEY (tenant_id) REFERENCES public."Tenant"(id);


--
-- Name: Tenant FK_Tenant_System_Of_Records_sor_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Tenant"
    ADD CONSTRAINT "FK_Tenant_System_Of_Records_sor_id" FOREIGN KEY (sor_id) REFERENCES public."System_Of_Records"(id);


--
-- Name: Vallia_Documents FK_Vallia_Documents_Vallia_Document_Categories_document_catego~; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Vallia_Documents"
    ADD CONSTRAINT "FK_Vallia_Documents_Vallia_Document_Categories_document_catego~" FOREIGN KEY (document_category_id) REFERENCES public."Vallia_Document_Categories"(id);


--
-- Name: Vallia_Sor_Document_Mappings FK_Vallia_Sor_Document_Mappings_System_of_Record_Folders_sor_f~; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Vallia_Sor_Document_Mappings"
    ADD CONSTRAINT "FK_Vallia_Sor_Document_Mappings_System_of_Record_Folders_sor_f~" FOREIGN KEY (sor_folder_id) REFERENCES public."System_of_Record_Folders"(id);


--
-- Name: Vallia_Sor_Document_Mappings FK_Vallia_Sor_Document_Mappings_Vallia_Documents_vallia_docume~; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Vallia_Sor_Document_Mappings"
    ADD CONSTRAINT "FK_Vallia_Sor_Document_Mappings_Vallia_Documents_vallia_docume~" FOREIGN KEY (vallia_document_id) REFERENCES public."Vallia_Documents"(id);


--
-- Name: Vallia_Sor_Field_Mappings FK_Vallia_Sor_Field_Mappings_System_Of_Record_Fields_sor_field~; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Vallia_Sor_Field_Mappings"
    ADD CONSTRAINT "FK_Vallia_Sor_Field_Mappings_System_Of_Record_Fields_sor_field~" FOREIGN KEY (sor_field_id) REFERENCES public."System_Of_Record_Fields"(id);


--
-- Name: Vallia_Sor_Field_Mappings FK_Vallia_Sor_Field_Mappings_Vallia_Fields_vallia_field_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Vallia_Sor_Field_Mappings"
    ADD CONSTRAINT "FK_Vallia_Sor_Field_Mappings_Vallia_Fields_vallia_field_id" FOREIGN KEY (vallia_field_id) REFERENCES public."Vallia_Fields"(id);


--
-- Name: Document_Extraction fk_tenant; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Document_Extraction"
    ADD CONSTRAINT fk_tenant FOREIGN KEY (tenant_id) REFERENCES public."Tenant"(id);


--
-- PostgreSQL database dump complete
--

