drop table tasks;
drop function task_status_notify;
drop trigger task_status_change;
drop table task_status;

create table task_owner(
owner VARCHAR(250) NOT NULL,
HEARTBEAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

create table task_topic(
topic VARCHAR(250) NOT NULL 
);

CREATE TABLE TASK (
TOPIC VARCHAR(250) NOT NULL,
SEQUENCE BIGSERIAL,
IDENTIFIER VARCHAR(500) NOT NULL,
STATE NUMERIC(1) DEFAULT 1 NOT NULL CHECK (STATE BETWEEN 0 AND 8),
DESCENT NUMERIC(1) DEFAULT 1 NOT NULL CHECK (DESCENT BETWEEN 1 AND 6),
OWNER VARCHAR(250),
CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
INPUT TEXT,
OUTPUT TEXT,
COMPLETED TIMESTAMP,
CONSTRAINT TASK_PK PRIMARY KEY (TOPIC, SEQUENCE)
)
PARTITION BY LIST (TOPIC);

CREATE INDEX TASK_BY_OWNER_IDX
ON TASK (STATE, OWNER);

CREATE INDEX TASK_BY_ID_IDX
ON TASK (TOPIC, IDENTIFIER, STATE, SEQUENCE);

CREATE FUNCTION TASK_TOPIC_FCT()
RETURNS TRIGGER AS
$BODY$
BEGIN
EXECUTE 'CREATE TABLE ' || QUOTE_IDENT('TASK_P_' || MD5(NEW.TOPIC)) || '
PARTITION OF TASK
FOR VALUES IN (' || QUOTE_LITERAL(NEW.TOPIC) || ')';
EXECUTE 'ALTER TABLE ' || QUOTE_IDENT('TASK_P_' || MD5(NEW.TOPIC)) || '
ADD CONSTRAINT ' || QUOTE_IDENT('TASK_TOPIC_REF_' || MD5(NEW.TOPIC)) || '
FOREIGN KEY (TOPIC) REFERENCES TASK_TOPIC (TOPIC)';
EXECUTE 'ALTER TABLE ' || QUOTE_IDENT('TASK_P_' || MD5(NEW.TOPIC)) || '
ADD CONSTRAINT ' || QUOTE_IDENT('TASK_OWNER_REF_' || MD5(NEW.TOPIC)) || '
FOREIGN KEY (OWNER) REFERENCES TASK_OWNER (OWNER)';
RETURN NEW;
END;
$BODY$
LANGUAGE PLPGSQL;

CREATE TRIGGER TASK_TOPIC_TRG
AFTER INSERT ON TASK_TOPIC
FOR EACH ROW
EXECUTE PROCEDURE TASK_TOPIC_FCT();

create view task_pretty as SELECT TOPIC, SEQUENCE, IDENTIFIER, CREATED, COMPLETED,
CASE
WHEN STATE = 0 THEN 'ACTIVE'
WHEN STATE = 1 THEN 'READY'
WHEN STATE = 2 THEN 'EXPIRED'
WHEN STATE = 3 THEN 'SUCCEEDED'
WHEN STATE = 4 THEN 'SUSPENDED'
WHEN STATE = 5 THEN 'FILTERED'
WHEN STATE = 6 THEN 'FAILED'
WHEN STATE = 8 THEN 'REDUNDANT'
WHEN DESCENT = 3 THEN 'SUCCEEDED'
WHEN DESCENT = 4 THEN 'SUSPENDED'
WHEN DESCENT = 5 THEN 'FILTERED'
WHEN DESCENT = 6 THEN 'FAILED'
ELSE 'unexpected value: ' || STATE || ' with descent of ' || DESCENT
END STATE,
CASE
WHEN STATE = 8 THEN 'YES'
ELSE 'NO'
END RECREATED,
INPUT,
OUTPUT
FROM TASK;